Test26   .ORIG
Test     .EQU    x3             ; 240 instructions. Should break the instruction limit.
Begin    ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         .END    Begin