Test25   .ORIG
Test     .EQU    x3             ; 120 instructions. Should compile.
Begin    ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         ADD     R0, R1, Test
         .END    Begin